export const ProductCard = [
    {
      id: 1,
      name: 'VERTICAL STRIPED SHIRT',
      price: 120,
      rating: 4.5,
      image: '/Frame 32 (1).png',
      discount: null,
    },
    {
      id: 2,
      name: 'COURAGE GRAPHIC T-SHIRT',
      price: 240,
      originalPrice: 260,
      rating: 3.5,
      discount: 20,
      image: '/Frame 33 (1).png',
    },
    {
      id: 3,
      name: 'LOOSE FIT BERMUDA SHORTS',
      price: 180,
      rating: 4.5,
      image: '/Frame 34 (1).png',
      discount: null,
    },
    {
      id: 4,
      name: 'LOOSE FIT BERMUDA SHORTS',
      price: 130,
      originalPrice: 160,
      rating: 4.5,
      discount: 30,
      image: '/Frame 38 (2).png',
    },
  ];